DROP SEQUENCE BOUND_CONDITION_SEQ;
DROP SEQUENCE SLIME_RESULT_SEQ;
DROP SEQUENCE FORTRESS_RESULT_SEQ;

DROP TABLE PARAMETRO;
DROP TABLE SLIME_RESULT;
DROP TABLE FORTRESS_RESULT;
DROP TABLE BOUND_CONDITION;

CREATE SEQUENCE BOUND_CONDITION_SEQ;
CREATE SEQUENCE SLIME_RESULT_SEQ;
CREATE SEQUENCE FORTRESS_RESULT_SEQ;

CREATE TABLE PARAMETRO (id INTEGER NOT NULL, VALOR VARCHAR NOT NULL);
CREATE TABLE SLIME_RESULT (id INTEGER NOT NULL, X INTEGER NOT NULL,Z INTEGER NOT NULL, NUMBER_OF_CHUNK INTEGER NOT NULL, JOB_EXECUTION_ID BIGINT);
CREATE TABLE FORTRESS_RESULT (id INTEGER NOT NULL, X INTEGER NOT NULL,Y INTEGER NOT NULL,Z INTEGER NOT NULL, TYPE INTEGER NOT NULL, JOB_EXECUTION_ID BIGINT);
CREATE TABLE BOUND_CONDITION (id INTEGER NOT NULL, SEED BIGINT NOT NULL, X INTEGER NOT NULL,Z INTEGER NOT NULL, RADIO INTEGER);